version: "2"

services:
  storage:
    image: postgres:10
    environment: 
      - POSTGRES_USER=admin 
      - POSTGRES_PASSWORD=admin 
      - POSTGRES_DB=monitor 
    ports:
      - 54323:5432
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on: 
      - storage